### ISSUE TITLE
the result cannot broadcast

### ISSUE THREAD

**Issue by RXien** [KingHodor/Ethereum-RLP#1]
i use the example result to broadcast:
f86c008504a817c80082520894e0defb92145fef3c3a945637705fafd3aa74a241880de0b6b3a7640000001ba009ebb6ca057a0535d6186462bc0b465b561c94a295bdb0621fc19208ab149a9ca0440ffd775ce91a833ab410777204d5341a6f9fa91216a6f3ee2c051fea6a0428

the error message is:
Error: rlp: non-canonical integer (leading zero bytes) for uint64, decoding into (types.Transaction)(types.txdata).AccountNonce

**Comment by KingHodor** [comment]
could you try it again? It should work now, I fixed the issue.
