### ISSUE TITLE
Chain ID Calculation needs to be improved

### ISSUE THREAD

**Issue by kwonssy02** [KingHodor/Ethereum-RLP#2]
Below two lines in RLP.c must be changed.
Your code just can create right RLP only when chain ID is small number.
 
https://github.com/KingHodor/Ethereum-RLP/blob/434eb4f82483bc90ee5e4d86409734c5d5eaee81/RLP.c#L37

https://github.com/KingHodor/Ethereum-RLP/blob/434eb4f82483bc90ee5e4d86409734c5d5eaee81/RLP.c#L80

Add below function and fix your code.
(I know this function is not great but can solve facing problem.)

```
int calculateLengOfV(uint32_t v) {
    // 1byte
    if ((v & 0xFF) == v) {
        return 1;        
    // 2byte
    } else if ((v & 0xFFFF) == v) {
        return 2;
    // 3byte
    } else if ((v & 0xFFFFFF) == v) {
        return 3;
    // 4byte
    } else if ((v & 0xFFFFFFFF) == v) {
        return 4;
    } else {
        return -1;
    }
}
```

And fix the code right.
```
totalLength += calculateLengOfV(new_tx->signature_v);

...

copyPos = wallet_copy_rpl(data + copyPos, &new_tx->signature_v, calculateLengOfV(new_tx->signature_v), copyPos);
```

**Comment by KingHodor** [comment]
I applied your fix.
